### ISSUE TITLE
Need to update to 1.20.5

### ISSUE THREAD

**Issue by casey-johnson** [SuperDarkOpenSource/minecraft-SuperDarkCore#24]
Update spigot version to 1.20.5

**Comment by cameronwhite4121** [comment]
![dadasdasdasda](https://github.com/SuperDarkOpenSource/minecraft-SuperDarkCore/assets/143460157/8795a1b5-0cbf-4ca4-9b0a-c11ed8730851)

**Comment by casey-johnson** [comment]
See https://github.com/SuperDarkOpenSource/minecraft-SuperDarkCore/pull/25
